theme = "autumn"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
j = "move_char_left"
k = "move_line_down"
l = "move_char_right"
i = "move_line_up"
s = "insert_mode"
S = "prepend_to_line"
n = "select_regex"
I = "split_selection"
